### ISSUE TITLE
Error when using aws_resource_missing_tags with module.

### ISSUE THREAD

**Issue by adrianocanofre** [terraform-linters/tflint-ruleset-aws#53] opened 2021-01-27 19:00 UTC
Error when using aws_resource_missing_tags with module.
```console
terraform init
tflint --module --config /path/validates.hcl
```

```hcl
rule "aws_resource_missing_tags" {
  enabled = true
  tags = ["Name", "purpose"]
}
```

```terraform
module "s3_bucket" {
  source = "terraform-aws-modules/s3-bucket/aws"

  bucket = "my-s3-bucket"
  acl    = "private"

  versioning = {
    enabled = true
  }

}
```

```output
tflint --module --config ./validate.hcl  --loglevel=trace
13:41:16 config.go:96: [INFO] Load config: ./validate.hcl
13:41:16 config.go:311: [DEBUG] Config loaded
13:41:16 config.go:312: [DEBUG]   Module: false
13:41:16 config.go:313: [DEBUG]   Force: false
13:41:16 config.go:314: [DEBUG]   IgnoreModules: map[string]bool{}
13:41:16 config.go:315: [DEBUG]   Varfiles: []string{}
13:41:16 config.go:316: [DEBUG]   Variables: []string{}
13:41:16 config.go:317: [DEBUG]   DisabledByDefault: false
13:41:16 config.go:318: [DEBUG]   Rules: map[string]*tflint.RuleConfig{"aws_resource_missing_tags":(*tflint.RuleConfig)(0xc000415800)}
13:41:16 config.go:319: [DEBUG]   Plugins: map[string]*tflint.PluginConfig{}
13:41:16 option.go:48: [DEBUG] CLI Options
13:41:16 option.go:49: [DEBUG]   Module: true
13:41:16 option.go:50: [DEBUG]   Force: false
13:41:16 option.go:51: [DEBUG]   IgnoreModules: map[string]bool{}
13:41:16 option.go:52: [DEBUG]   EnableRules: []string(nil)
13:41:16 option.go:53: [DEBUG]   DisableRules: []string(nil)
13:41:16 option.go:54: [DEBUG]   Only: []string(nil)
13:41:16 option.go:55: [DEBUG]   Varfiles: []string{}
13:41:16 option.go:56: [DEBUG]   Variables: []string{}
13:41:16 loader.go:57: [INFO] Initialize new loader
13:41:16 loader.go:68: [INFO] Module manifest file found. Initializing...
13:41:16 loader.go:291: [DEBUG] Parsing the module manifest file: {"Modules":[{"Key":"","Source":"","Dir":"."},{"Key":"s3_bucket","Source":"terraform-aws-modules/s3-bucket/aws","Version":"1.17.0","Dir":".terraform/modules/s3_bucket"}]}
13:41:16 loader.go:82: [INFO] Load configurations under .
13:41:16 loader.go:97: [INFO] Module inspection is enabled. Building a root module with children...
13:41:16 loader.go:273: [DEBUG] Trying to load the module: key=module.s3_bucket, version=1.17.0, dir=.terraform/modules/s3_bucket
13:41:16 loader.go:170: [INFO] Load values files
13:41:16 runner.go:50: [INFO] Initialize new runner for root
13:41:16 runner.go:50: [INFO] Initialize new runner for module.s3_bucket
13:41:16 inspect.go:48: [INFO] AWS provider requirements found. Enable the plugin `aws` automatically
13:41:16 discovery.go:54: [INFO] Plugin `aws` is not installed, but bundled plugins are available.
13:41:16 discovery.go:68: [INFO] Plugin `aws` found
13:41:16 provider.go:62: [INFO] Prepare rules
13:41:16 provider.go:90: [INFO]   3 rules enabled
13:41:16 terraform_deprecated_interpolation.go:48: [TRACE] Check `terraform_deprecated_interpolation` rule for `root` runner
13:41:16 terraform_module_pinned_source.go:72: [TRACE] Check `terraform_module_pinned_source` rule for `root` runner
13:41:16 terraform_module_pinned_source.go:81: [DEBUG] Walk `s3_bucket.source` attribute
13:41:16 terraform_workspace_remote.go:48: [TRACE] Check `terraform_workspace_remote` rule for `root` runner
13:41:16 runner_walk.go:36: [DEBUG] Walk `aws_s3_bucket.this.acl` attribute
13:41:16 runner_walk.go:36: [DEBUG] Walk `aws_s3_bucket.this.acceleration_status` attribute
13:41:16 runner_eval.go:137: [WARN] Null value found in .terraform/modules/s3_bucket/main.tf:9; TFLint ignores an expression includes an null value.
13:41:16 runner_walk.go:36: [DEBUG] Walk `aws_s3_bucket.this.request_payer` attribute
13:41:16 runner_eval.go:137: [WARN] Null value found in .terraform/modules/s3_bucket/main.tf:10; TFLint ignores an expression includes an null value.
```
## Version

```console
$ tflint -v
TFLint version 0.23.1
+ ruleset.aws (0.1.2-bundled)
$ terraform -v
Terraform v0.13.5
```

How can I solved this problem?

**Comment by bendrucker** [comment] 2021-01-27 19:24
Errors found in child modules are broadcast upwards and then associated with the calling attribute in the `module` block. You'll find that this works:

```tf
module "s3_bucket" {
  source = "terraform-aws-modules/s3-bucket/aws"

  bucket = "my-s3-bucket"
  acl    = "private"

  versioning = {
    enabled = true
  }
  
  tags = {}
}
```

```
1 issue(s) found:

Notice: The resource is missing the following tags: "Name", "purpose". (aws_resource_missing_tags)

  on main.tf line 11:
  11:   tags = {}

Callers:
   main.tf:11,10-12
   .terraform/modules/s3_bucket/main.tf:7,25-33

Reference: https://github.com/terraform-linters/tflint-ruleset-aws/blob/v0.1.2/docs/rules/aws_resource_missing_tags.md
```

In this case the fix will involve modifying upstream TFLint behavior to associate these errors with the entire `module` block rather than trying to use the range from a calling attribute.

**Comment by adrianocanofre** [comment] 2021-01-27 20:15
when I pass the variable in the module the config works, but in my case I need to validate even when not added inside the module.

**Comment by bendrucker** [comment] 2021-01-27 20:16
Yep, it's a bug, just explaining

**Comment by bendrucker** [comment] 2022-12-07 18:55
On further review, this is working as designed, even if it's confusing/undesirable. `--module` mode detects errors caused by variables passed to a module. It does not mean "recursively check all my modules."

This behavior is important for avoiding spurious errors. You might, for example, require that all variables in your configuration have a `description`. But if you source a third party module, enforcing that ends up generating warnings for modules you can't readily change (without forking). 

TFLint's goal is to catch errors early, not to provide critical enforcement. Computing tags has become increasingly complex with multiple sources of config, including the provider. We can try to make improvements but ultimately anyone needing strict enforcement of tagging (e.g. for cost tracking) should be enforcing that against a Terraform plan, not the static configuration. Terraform Cloud offers some options, including Sentinel and OPA policies, or Run Tasks for third party integrations. 

I'm closing this out for now since this is not addressable without meaningfully changing how TFLint's module mode works. It's possible we'll revisit but for now this limitation is the intended behavior.

**Closed by bendrucker** 2022-12-07 18:55 UTC
